### ISSUE TITLE
script parameters

### ISSUE THREAD

**Issue by rumski20** [sam-giebner/advanced-python-workshop#1]
You ever use these?

I was doing some coding today (🤯 ) and realized we didn't talk about script parameters. This could maybe fall under the `advanced` category.
I use them a bit.
They range from the basic:
```python
# get all the layers
# unless specified by script arg
if len(sys.argv) > 1:
    layers = sys.argv[1].split(',')
else:
    layers = cat.get_layers()
```

To more advanced:
```python
# Parse command line arguments
parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
parser.add_argument(
    "-c",
    "--catalog",
    help="Path to data catalog CSV file",
)  
args = vars(parser.parse_args())
```

What do you think?

**Comment by sam-giebner** [comment]
Not a bad thought. The advanced example was new to me. I don't often use command line arts but maybe I should reconsider?
